<?php

return [
    'inspirations' => [
        'best beginner ios projects to build',
        'daily drawing prompts for creativity',
        'how to learn vietnamese southern dialect',
        'minimal home office inspiration',
        'motorcycle cafe racer build guide',
        'coding music lofi mix',
        'photography golden hour tips',
        'react accessibility checklist',
        'javascript performance best practices',
        'healthy jamaican recipes quick',
    ],
    'defaults' => [
        'Auirah tasks',
        'Auirah notes',
        'learn swiftui',
        'three.js space shooter',
        'how to set up mysql on mac',
        'best figma color palettes',
        'square api payments',
        'binance api docs',
        'firebase firestore rules',
        'laravel hostinger deploy',
    ],
    'curated' => [
        [
            'id' => 'tasks-overview',
            'title' => 'Stay on top of your tasks',
            'snippet' => 'Capture quick todos and long-form goals with reminders that sync across the Auirah suite.',
            'url' => '/tasks',
            'type' => 'tasks',
        ],
        [
            'id' => 'notes-quick',
            'title' => 'Ideas, drafts, and daily notes',
            'snippet' => 'Organise inspirations with tags, colours, and collaborative sharing for the whole family.',
            'url' => '/notes',
            'type' => 'notes',
        ],
        [
            'id' => 'music-focus',
            'title' => 'Focus playlists that energise',
            'snippet' => 'Stream curated ambient and lofi mixes while you build, study, or unwind late at night.',
            'url' => '/music',
            'type' => 'music',
        ],
        [
            'id' => 'photos-memories',
            'title' => 'Memories in vibrant colour',
            'snippet' => 'Upload and relive your favourite shots with smart albums, face recognition, and quick share links.',
            'url' => '/photos',
            'type' => 'photos',
        ],
        [
            'id' => 'learn-paths',
            'title' => 'Learning paths for curious minds',
            'snippet' => 'Discover curated lessons, books, and bite-sized workshops tailored to your current focus.',
            'url' => '/learn',
            'type' => 'learn',
        ],
        [
            'id' => 'maps-weekend',
            'title' => 'Maps that know your weekend plans',
            'snippet' => 'Plot adventures with favourite spots, offline guides, and location sharing that respects privacy.',
            'url' => '/maps',
            'type' => 'maps',
        ],
        [
            'id' => 'article-hostinger',
            'title' => 'Deploy Laravel APIs on Hostinger',
            'snippet' => 'Step-by-step guide for configuring PHP 8.2, Composer, and queues for resilient deployments.',
            'url' => 'https://www.hostinger.com/tutorials/laravel',
            'type' => 'article',
        ],
    ],
];
